apiVersion: apps/v1
kind: Deployment
metadata:
  name: chubz-deployment
  labels:
    app: chubz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chubz
  template:
    metadata:
      labels:
        app: chubz
    spec:
      containers:
      - name: chubz
        image: tamalerhino/chubby-unicorn:latest
        ports:
        - containerPort: 80
