apiVersion: v1
kind: Service
metadata:
  name: chubz-service
  labels:
    app: chubz-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chubz
  sessionAffinity: None
